ansible_user: boboysdadda
ansible_ssh_private_key_file: /home/boboysdadda/.ssh/id_ed25519
ansible_become: yes
ansible_become_method: sudo
network_cidr: 9
network_gateway: 10.0.0.1
network_dns: 10.0.0.1